server:
  port: 8888
spring:
  application:
     name: gateway-service
  cloud:
    gateway:
      routes:
        - id: r1
          uri: lb://CUSTOMER-SERVICE
          predicates:
            - Path=/customers/**
        - id: r2
          uri: lb://INVENTORY-SERVICE
          predicates:
            - Path=/products/**
    discovery:
      enabled: true
    config:
      enabled: false

management:
  endpoints:
    web:
      exposure:
        exclude: '*'


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true