server:
  port: 8888
spring:
  application:
     name: gateway-service
  cloud:
    gateway:
      routes:
        - id: r1
          uri: lb://CUSTOMER-SERVICE
          predicates:
            - Path=/customers/**
        - id: r2
          uri: lb://INVENTORY-SERVICE
          predicates:
            - Path=/products/**
        - id: r3
          uri: lb://BILLING-SERVICE
          predicates:
              - Path=/paytech/**
    discovery:
      enabled: true
      locator:
        lower-case-service-id: true # transform microservice's name in Uppercase
    config:
      enabled: false

management:
  endpoints:
    web:
      exposure:
        exclude: '*'


eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
