server:
  port: 8082
spring:
  application:
    name : inventory-service
  cloud:
    discovery:
      enabled: true # activer la connexion vers discovery service inexistant
    config:
      enabled: false # désactiver la connexion vers service de configuration
  jpa:
    database: mysql
    hibernate:
      ddl-auto: create
    show-sql: true
  datasource:
    url: jdbc:mysql://localhost:3305/product-db?createDatabaseIfNotExist=true
    password: user123
    username: user

# activer tous les endpoints d'actuator
management:
  endpoints:
    web:
      exposure:
        exclude: '*'
#définir la zone d'inscription du discovery

eureka:
  client:
    register-with-eureka: true  # Ensure registration is enabled
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/

  instance:
    prefer-ip-address: true