services:

  mysql-customer-db:
    image: mysql:8.0
    container_name: container_mysql-customer-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: customer-db
      MYSQL_USER: user
      MYSQL_PASSWORD: user123
    ports:
      - "3306:3306"
    volumes:
      - customer_mysql_data:/var/lib/mysql
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -u $$MYSQL_USER --password=$$MYSQL_PASSWORD


  phpmyadmin-customer-db:
    container_name: container_phpmyadmin-customerdb
    image: phpmyadmin/phpmyadmin:latest
    ports:
      - "8085:80"
    environment:
      MYSQL_ROOT_PASSWORD: root
      PMA_HOST: mysql-customer-db
      PMA_USER: user
      PMA_PASSWORD: user123
    depends_on:
      - mysql-customer-db
    restart: unless-stopped



volumes:
  customer_mysql_data:
    driver: local